module.exports = [
  {
    trailName: "Jackson Falls Trail",
    image: "https://h8k7j2g6.rocketcdn.me/wp-content/uploads/2021/04/main-falls-1.jpg",
    mapsLink: "https://goo.gl/maps/jMwSJQ9bK6ezE9XW8",
    description: "Has some of the best rock climbing in Illinois, the short Rim Rock Recreational Trail, and the Garden of the Gods, featuring sandstone formations 320 million years old.",
    length: 4.5,
    difficulty: "⭐⭐⭐",
    quality: "⭐⭐⭐⭐",
  },
  {
    trailName: "Midewin National Tallgrass Prairie",
    image: "https://images.squarespace-cdn.com/content/v1/567070822399a343227dd9c4/1452709859398-MMZ8ZFFBB69DQAV77XXF/image-asset.jpeg",
    mapsLink: "https://goo.gl/maps/PQAUPy3WUKBzuatm8",
    description: "The river ensures there’s a variety of nature to be seen, and the park’s trail system offers hiking and biking routes, and is even open for snowmobiling in the winter.",
    length: 3,
    difficulty: "⭐⭐",
    quality: "⭐⭐⭐",
  },
  {
    trailName: "Kankakee River Stat Park Trail",
    image: "https://static.rootsrated.com/image/upload/s--O-B5yjnO--/t_rr_large_traditional/ng53b2rni7578tzo3slu.jpg",
    mapsLink: "https://goo.gl/maps/9sMdSmPJi5grhkKZ8",
    description: "Established in 1996 as the nation’s first designated tallgrass prairie, with work ongoing to restore this endangered ecosystem, including the introduction of a herd of bison..",
    length: 29,
    difficulty: "⭐⭐⭐⭐⭐",
    quality: "⭐⭐",
  },
  {
    trailName: "Waterfall Glen Forest Preserve",
    image: "https://openlands.org/wp-content/uploads/2019/05/Waterfall-Glen-2048x1365.jpg",
    mapsLink: "https://goo.gl/maps/ytextxa9Gi31YUiUA",
    description: "The main trail is a 9.5-mile loop around the preserve on a limestone surface, with a number of inclines that make it a good workout. Unmarked paths off the main trail can also be explored, but be cautious, as they may not rejoin the loop. In addition to hiking, camping and fishing on the Des Plains River are other recreational draws.",
    length: 11,
    difficulty: "⭐⭐⭐⭐⭐",
    quality: "⭐⭐⭐",
  },
  {
    trailName: "Ferne Clyffe State Park",
    image: "https://i0.wp.com/midwestnomads.com/wp-content/uploads/2020/05/ferneclyf5-scaled.jpg?fit=2560%2C1707&ssl=1",
    mapsLink: "https://goo.gl/maps/4XkdRUcFHsG3FKyR8",
    description: "Visiting after a heavy rainfall will ensure the waterfall is flowing nicely, and it can be explored up close by climbing a number of paths that reach the top. Otherwise, most of the trails wind between picturesque woods, with interesting rock formations to explore.",
    length: 2.1,
    difficulty: "⭐",
    quality: "⭐⭐⭐⭐⭐",
  },
]
